# Generated by Django 4.1 on 2023-07-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(max_length=255)),
                ("no_of_guests", models.PositiveIntegerField(max_length=6)),
                ("booking_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=5, primary_key=True, serialize=False),
                ),
                ("title", models.TextField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField(max_length=5)),
            ],
        ),
    ]
