# Generated by Django 4.1 on 2023-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_delete_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
