# Generated by Django 4.1 on 2023-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_booking_reservation_slot_menu_menu_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(),
        ),
    ]
